In [1]:
#quantization demo
import numpy as np

def calc_memory(matrix):
    return matrix.nbytes * 8

def quantize_matrix(matrix):
    return np.round(matrix * 127).astype(np.int8)

ogMatrix = np.array([[.002123, .88533, .12055], [.94944, .1345, .913], [.0002, .0023, .0024]])
print("Matrix:")
print(ogMatrix)
print("Memory of matrix : " + str(calc_memory(ogMatrix)) + "\n")

qMatrix = quantize_matrix(ogMatrix)
print("Quantized Matrix:")
print(qMatrix)
print("Memory of quantized matrix : " + str(calc_memory(qMatrix)))


Matrix:
[[2.1230e-03 8.8533e-01 1.2055e-01]
 [9.4944e-01 1.3450e-01 9.1300e-01]
 [2.0000e-04 2.3000e-03 2.4000e-03]]
Memory of matrix : 576

Quantized Matrix:
[[  0 112  15]
 [121  17 116]
 [  0   0   0]]
Memory of quantized matrix : 72
