In [30]:
import torch

In [31]:
words = open('names.txt', 'r').read().splitlines() #dataset

In [32]:
map = {
    'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5,
    'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10,
    'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15,
    'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20,
    'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25,
    'z': 26, '.': 0
}

In [40]:
#bigram dataset
xs, ys = [], []

for w in words[:1]:
    chs = ['.'] + list(w) + ['.']
    for ch1, ch2 in zip(chs, chs[1:]):
        print(ch1, ch2) #character bigrams !
        #print(map.get(ch1), map.get(ch2))
        xs.append(map.get(ch1))
        ys.append(map.get(ch2))

x_tensor = torch.tensor(xs)
y_tensor = torch.tensor(ys)

. e
e m
m m
m a
a .


In [50]:
x_tensor #input X values

tensor([ 0,  5, 13, 13,  1])

In [52]:
y_tensor #input Y values

tensor([ 5, 13, 13,  1,  0])

In [65]:
# one hot encode the x tensors
import torch.nn.functional as F
xencoded = F.one_hot(x_tensor, num_classes=27).float()

In [67]:
print(xencoded.shape)
xencoded

torch.Size([5, 27])


tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [69]:
#### NN PART ####

In [73]:
# initialize randomly 27 neurals weights. each neuron has 27 inputs

g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator=g)

In [77]:
# forward pass
xencoded = F.one_hot(x_tensor, num_classes=27).float()
logits = xencoded @ W
counts = logits.exp()
probs = counts / counts.sum(1, keepdims=True)